spring.application.name:
  volume-api

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1
        options:
          temperature: 0.7
          top-p: 0.9
          max-tokens: 512
    mcp:
      client:
        sse:
          connections:
            volume-tool-server:
              url: http://localhost:8081