spring.application.name:
  volume-api

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1
        options:
          temperature: 0.7
          top-p: 0.9
          max-tokens: 512
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_CLOUD_PROJECT_ID:your-google-cloud-project-id}
          location: us-central1
          api-key: ${GEMINI_API_KEY:your-gemini-api-key-here}
          chat:
            model: gemini-1.5-pro
            options:
              temperature: 0.7
              top-p: 0.9
              max-tokens: 1024
    mcp:
      client:
        sse:
          connections:
            volume-tool-server:
              url: http://localhost:8081